# Generated by Django 5.0.2 on 2024-12-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('seller', 'Sotuvchi'), ('delivery', 'Yetkazib beruvchi')], default='seller', max_length=20, verbose_name='Roli'),
        ),
    ]
