# Generated by Django 5.0.2 on 2024-12-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='asdf', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
