# Generated by Django 5.0.2 on 2024-12-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('seller', 'Sotuvchi'), ('delivery', 'Yetkazib beruvchi'), ('boss', 'Boshliq')], default='seller', max_length=20, verbose_name='Roli'),
        ),
    ]
