# Generated by Django 5.0.2 on 2024-12-27 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Bo'lim Nomi")),
                ('employee_limit', models.PositiveIntegerField(verbose_name='Maksimal Xodimlar Soni')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Lavozim Nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Xodim Ismi')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Oylik Maosh')),
                ('employment_type', models.CharField(max_length=50, verbose_name='Ish Turi')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Telefon Raqami')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.department', verbose_name="Bo'lim")),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.position', verbose_name='Lavozim')),
            ],
        ),
    ]
