version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: furniture_factory_backend_web
    command: /start
    volumes:
      - .:/app
    ports:
      - 8010:8010
    env_file:
      - ./env/.local
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - furniture_factory_data:/var/lib/postgresql/data/
    env_file:
      - ./env/.local

volumes:
  furniture_factory_data: