# Generated by Django 5.0.2 on 2024-12-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('collection', "Yig'ish"), ('delivery', 'Yetkazib Berish'), ('exportation', 'Olib Ketish')], max_length=20),
        ),
    ]
