# Generated by Django 5.0.2 on 2025-02-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_cost',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
