# Generated by Django 5.0.2 on 2025-02-23 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0006_alter_order_order_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('future_stock', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='factory.product')),
            ],
        ),
    ]
