# Generated by Django 5.0.2 on 2025-02-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0007_futurestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurestock',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
