# Generated by Django 5.0.2 on 2025-02-23 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0008_futurestock_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('future_stock', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('finished', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.product')),
            ],
        ),
        migrations.DeleteModel(
            name='FutureStock',
        ),
    ]
