# Generated by Django 5.0.2 on 2025-04-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0010_futurestock_delete_futurestocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approved_by_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='approved_by_seller',
            field=models.BooleanField(default=False),
        ),
    ]
