# Generated by Django 5.0.2 on 2025-04-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0011_order_approved_by_delivery_order_approved_by_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approved_by_delivery',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='approved_by_seller',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
